### PR TITLE
refactor: read package.json using require

### PR DESCRIPTION
**Pull request by felixmosh**
Small improvement over read & parse

### CODE REVIEW

**Comment by Platane** [comment]
Hi @felixmosh thanks for your interest in this package.
Sorry for leaving your PR opened for a while, I was on vacation.

It seems that you are using "lf" end of line style. which makes the diff confusing since I used crlf. I use .editorconfig to automate this annoying configuration.

Would you mind if I commit over this branch with crlf style ?

**Comment by felixmosh** [comment]
Sure, will do it later today

**Comment by felixmosh** [comment]
Done :]

Consider adding `.gitattributes` that will force CRLF (even thought git converts by default to LF)
https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings#per-repository-settings

**Comment by Platane** [comment]
Awesome thanks for the tips :+1:

**Pull request merged**
